### PR TITLE
Revert "Add extended naturals as coalgebra"

### PR DESCRIPTION
**Pull request by bgavran**
Uh, I jumped the gun by accepting this. The final coalgebra of these endofunctors are notoroiously problematic to write down in a satisfying fashion. See [here](https://twitter.com/bgavran3/status/1598039207951634434)

More specifically - for A + X - we can't know the final A if we keep going on forever!

### CODE REVIEW

**Comment by bgavran** [comment]
@jasoncarr0

**Comment by jasoncarr0** [comment]
Ah I never noticed the notification for this: only the natural numbers version was correct. But in any case the definition was specifically in `Set` as a model of ZFC, i.e. classical logic in which we can determine if the sequence is infinite or not.

**Comment by jasoncarr0** [comment]
Ah @bgavran  I never noticed the notification for this: only the natural numbers version was correct. But in any case the definition was specifically in `Set` as a model of ZFC, i.e. classical logic in which we can determine if the sequence is infinite or not.

**Comment by jasoncarr0** [comment]
Constructively it would suffice to consider the "one-point compactification", with the naturals it's easily defined as a non-decreasing binary sequence, i.e. examples like 00000011111..., or 0000000000... for an infinite sequence.

**Pull request merged**
